import { expect, test } from '@playwright/test'
import dayjs from 'dayjs'

test.beforeEach(async ({ page }) => {
  const response = await page.request.post('/api/auth/login', {
    data: { username: 'admin', password: 'admin-pass' },
  })
  expect(response.ok()).toBe(true)
})

test('未登录用户会跳转登录页', async ({ page }) => {
  await page.context().clearCookies()
  expect((await page.request.get('/api/data')).status()).toBe(401)
  await page.goto('/zh/settings')
  await expect(page).toHaveURL(/\/login$/)
  await expect(page.getByRole('button', { name: '登录' })).toBeVisible()
  await expect(page.getByText('访客账号：readonly-demo readonly-demo-pass')).toBeVisible()
})

test('只读访客不显示写入和导出入口', async ({ page }) => {
  await page.context().clearCookies()
  const login = await page.request.post('/api/auth/login', {
    data: { username: 'viewer', password: 'viewer-pass' },
  })
  expect(login.ok()).toBe(true)
  await page.goto('/zh/')
  await expect(page.getByText('只读访客').first()).toBeVisible()
  await expect(page.getByRole('button', { name: /快速记录/ })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '＋ 睡眠' })).toHaveCount(0)
  await page.goto('/zh/settings')
  await expect(page.getByText('当前账号为只读访客')).toBeVisible()
  await expect(page.getByRole('button', { name: /下载 JSON|导出 CSV|恢复数据/ })).toHaveCount(0)

  const initial = await page.request.get('/api/data')
  const data = await initial.json()
  const denied = await page.request.put('/api/data', {
    headers: { 'If-Match': initial.headers().etag },
    data,
  })
  expect(denied.status()).toBe(403)
})

test('退出后需要重新登录', async ({ page }) => {
  await page.goto('/zh/')
  await page.getByRole('button', { name: '退出' }).click()
  await expect(page).toHaveURL(/\/login$/)
})

test('桌面端使用顶部导航并展示概览入口', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop')
  await page.goto('/zh/')
  await expect(page.locator('a:visible').filter({ hasText: 'TrackFit' }).first()).toBeVisible()
  await expect(page.locator('aside')).toHaveCount(0)
  await expect(page.getByRole('navigation', { name: '主导航' }).getByRole('link')).toHaveCount(5)
  const repositoryLink = page.getByRole('link', { name: 'GitHub 仓库：01Petard/TrackFit' })
  await expect(repositoryLink).toBeVisible()
  await expect(repositoryLink).toHaveAttribute('href', 'https://github.com/01Petard/TrackFit')
  await expect(repositoryLink).toHaveAttribute('target', '_blank')
  await expect(page.getByRole('button', { name: /快速记录/ })).toBeVisible()
  await expect(page.locator('a[href="/zh/analysis"]:visible').first()).toBeVisible()
  const mainNavigation = page.getByRole('navigation', { name: '主导航' })
  const homeNavigation = mainNavigation.getByRole('link', { name: '主页' })
  const settingsNavigation = mainNavigation.getByRole('link', { name: '设置' })
  await expect(homeNavigation).not.toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(homeNavigation).not.toHaveCSS('color', await settingsNavigation.evaluate(element => getComputedStyle(element).color))
  const recordsButton = page.getByRole('button', { name: '测量记录', exact: true })
  await expect(recordsButton).toBeVisible()
  await expect(page.getByRole('button', { name: '指标管理', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: /进入行为记录/ })).toBeVisible()
  await expect(page.locator('nav a:visible')).toHaveCount(5)
  await expect(page.locator('nav a[href="/records"]:visible')).toHaveCount(0)
  await expect(page.locator('nav a[href="/zh/analysis"]:visible')).toHaveCount(1)
  await expect(page.locator('nav a[href="/metrics"]:visible')).toHaveCount(0)
  await expect(page.locator('nav a[href="/zh/behavior"]:visible')).toHaveCount(1)
  await recordsButton.click()
  await expect(page.getByRole('dialog', { name: '测量记录' })).toBeVisible()
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole('button', { name: '关闭测量记录' }).click()
  await page.getByRole('button', { name: '指标管理', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '指标管理' })).toBeVisible()
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole('button', { name: '关闭指标管理' }).click()

  const navigationHeader = page.locator('header.sticky')
  await page.evaluate(() => window.scrollTo({ top: 700, behavior: 'instant' }))
  await expect(navigationHeader).toHaveClass(/-translate-y-full/)
  await page.evaluate(() => window.scrollTo({ top: 300, behavior: 'instant' }))
  await expect(navigationHeader).toHaveClass(/translate-y-0/)
})

test('手机端可以打开测量表单', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile')
  await page.goto('/zh/')
  await page.getByRole('button', { name: /快速记录/ }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(page.getByText('同一天可以记录任意多次')).toBeVisible()
  await expect(page.getByText('所有已启用指标均可直接填写')).toBeVisible()
  await expect(dialog.getByText('腰围', { exact: true })).toBeVisible()
  await expect(page.locator('details')).toHaveCount(0)
  await dialog.getByRole('button', { name: /\d{4}\/\d{1,2}\/\d{1,2}/ }).click()
  await page.getByLabel('具体时间').fill('08:30:15')
  await page.getByRole('button', { name: '完成', exact: true }).click()
  await expect(dialog.getByRole('button', { name: /8:30:15/ })).toBeVisible()
})

test('首页可以快捷记录睡眠和训练', async ({ page }) => {
  await page.goto('/zh/')

  await page.getByRole('button', { name: '＋ 睡眠' }).click()
  await expect(page.getByRole('heading', { name: '新增睡眠记录' })).toBeVisible()
  await page.getByRole('dialog').getByRole('button', { name: '×' }).click()

  await page.getByRole('button', { name: '＋ 训练' }).click()
  await expect(page.getByRole('heading', { name: '新增训练记录' })).toBeVisible()
})

test('补记支持体重和训练自选日期，体重默认使用最近记录', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop')
  const initial = await page.request.get('/api/data')
  const original = await initial.json()
  const firstDay = dayjs().subtract(3, 'day').hour(8).minute(0).second(0)
  const customDay = dayjs().subtract(2, 'day').format('YYYY-MM-DD')
  try {
    const seeded = await page.request.put('/api/data', {
      headers: { 'If-Match': initial.headers().etag! },
      data: { ...original, settings: original.settings.map((item: object) => ({ ...item, desiredWeightMinimum: 70, desiredWeightMaximum: 75 })), bodyRecords: [{ id: 1, measuredAt: firstDay.subtract(1, 'day').toISOString(), note: null, values: [{ metricId: 1, value: 72.5 }] }, { id: 2, measuredAt: firstDay.toISOString(), note: null, values: [{ metricId: 1, value: 72.67 }] }], trainingRecords: [], sleepRecords: [] },
    })
    expect(seeded.ok()).toBe(true)
    await page.goto('/zh/')
    await expect(page.getByRole('link', { name: '查看完整记录分析 →' })).toHaveAttribute('href', '/zh/analysis')
    await expect(page.getByText('当前体重在目标区间内')).toHaveCount(0)
    await expect(page.getByText(/当前体重处于个人目标区间/)).toHaveCount(0)
    await page.getByRole('link', { name: '查看完整记录分析 →' }).click()
    await expect(page.getByText('当前体重在目标区间内')).toBeVisible()
    await page.goto('/zh/')

    await page.getByRole('button', { name: /快速记录/ }).click()
    const measurementDialog = page.getByRole('dialog')
    const currentWeight = measurementDialog.getByLabel('体重（kg）', { exact: true })
    await expect(currentWeight).toHaveValue('72.67')
    await expect(currentWeight).toHaveAttribute('step', '0.01')
    await measurementDialog.getByRole('button', { name: '×' }).click()

    await page.getByRole('button', { name: '补记' }).first().click()
    const dialog = page.getByRole('dialog')
    const weight = dialog.getByLabel('体重', { exact: true })
    await expect(weight).toHaveValue('72.67')
    await expect(weight).toHaveAttribute('step', '0.01')
    await dialog.getByLabel('测量日期').fill(customDay)
    await dialog.getByRole('button', { name: '体重 +' }).click()
    await expect(weight).toHaveValue('72.68')
    await dialog.getByRole('button', { name: '保存记录' }).click()
    await expect(dialog).toBeHidden()

    const trainingCard = page.locator('article').filter({ hasText: '今日训练' }).first()
    await trainingCard.getByRole('button', { name: '补记' }).click()
    await dialog.getByLabel('训练日期').fill(customDay)
    await dialog.getByLabel('训练时间').fill('15:45')
    const trainingDay = (await dialog.getByRole('heading', { level: 2 }).textContent())!.match(/\d{4}-\d{2}-\d{2}/)![0]
    await dialog.getByRole('button', { name: '保存记录' }).click()
    await expect(dialog).toBeHidden()

    const stored = await (await page.request.get('/api/data')).json()
    expect(stored.bodyRecords.some((record: { measuredAt: string, values: { value: number }[] }) => dayjs(record.measuredAt).format('YYYY-MM-DD') === customDay && record.values.some(value => value.value === 72.68))).toBe(true)
    expect(stored.trainingRecords.some((record: { recordedAt: string }) => dayjs(record.recordedAt).format('YYYY-MM-DD HH:mm') === `${trainingDay} 15:45`)).toBe(true)
    expect(trainingDay).toBe(customDay)
  } finally {
    const current = await page.request.get('/api/data')
    const restored = await page.request.put('/api/data', { headers: { 'If-Match': current.headers().etag! }, data: original })
    expect(restored.ok()).toBe(true)
  }
})

test('记录页使用统一日期选择器', async ({ page }) => {
  await page.goto('/zh/records')
  await page.getByRole('button', { name: '不限开始日期' }).click()
  await expect(page.getByRole('button', { name: '今天', exact: true })).toBeVisible()
})

test('就寝时间滚轮支持取消、跨日保存和重新编辑', async ({ page }) => {
  await page.goto('/zh/behavior')
  await page.getByRole('button', { name: '＋ 睡眠' }).click()
  const bedtime = page.getByRole('button', { name: /^就寝时间：/ })
  const original = await bedtime.textContent()
  await bedtime.click()
  const hours = page.getByRole('spinbutton', { name: '小时', exact: true })
  const minutes = page.getByRole('spinbutton', { name: '分钟', exact: true })
  await expect(hours).toBeVisible()
  await hours.press('End')
  await minutes.press('Home')
  await minutes.press('ArrowUp')
  await expect(hours).toHaveAttribute('aria-valuenow', '23')
  await expect(minutes).toHaveAttribute('aria-valuenow', '1')
  await page.getByRole('button', { name: '取消', exact: true }).last().click()
  await expect(bedtime).toHaveText(original!)

  await bedtime.click()
  await hours.press('End')
  await minutes.press('End')
  await expect(minutes).toHaveAttribute('aria-valuenow', '59')
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(bedtime).toContainText('23:59')
  await expect(page.getByText(/起床时间：.*7:59/)).toBeVisible()
  const selectedDate = (await bedtime.textContent())!.match(/\d{4}\/\d{1,2}\/\d{1,2}/)![0]
  const save = page.waitForResponse(response => response.url().includes('/api/data') && response.request().method() === 'PUT')
  await page.getByRole('button', { name: '保存记录', exact: true }).click()
  expect((await save).ok()).toBe(true)
  const stored = await (await page.request.get('/api/data')).json()
  const expectedBedtime = await page.evaluate(date => new Date(`${date.replaceAll('/', '-')} 23:59:00`).toISOString(), selectedDate)
  const saved = stored.sleepRecords.find((record: { fellAsleepAt: string }) => record.fellAsleepAt === expectedBedtime)
  expect(saved).toBeTruthy()
  expect(new Date(saved.wokeUpAt).getTime() - new Date(saved.fellAsleepAt).getTime()).toBe(8 * 60 * 60 * 1000)

  const record = page.locator('tr:visible, article:visible').filter({ hasText: /分数 80/ }).filter({ has: page.getByRole('button', { name: '编辑' }) }).first()
  await record.getByRole('button', { name: '编辑' }).click()
  await bedtime.click()
  await expect(hours).toHaveAttribute('aria-valuenow', '23')
  await expect(minutes).toHaveAttribute('aria-valuenow', '59')
  await page.getByRole('button', { name: '取消', exact: true }).last().click()
  await page.locator('form').getByRole('button', { name: '取消', exact: true }).click()
  page.once('dialog', prompt => prompt.accept())
  await record.getByRole('button', { name: '删除' }).click()
})

test('就寝时间滚轮可滚动且小屏操作按钮不溢出', async ({ page }, testInfo) => {
  await page.goto('/zh/')
  await page.getByRole('button', { name: '＋ 睡眠' }).click()
  await page.getByRole('button', { name: /^就寝时间：/ }).click()
  const minutes = page.getByRole('spinbutton', { name: '分钟', exact: true })
  await minutes.press('Home')
  await minutes.hover()
  await page.mouse.wheel(0, 220)
  await expect.poll(async () => Number(await minutes.getAttribute('aria-valuenow'))).toBeGreaterThan(0)
  const confirm = page.getByRole('button', { name: '确定', exact: true })
  await expect(confirm).toBeInViewport({ ratio: 1 })
  await page.screenshot({ path: testInfo.outputPath('bedtime-wheel.png') })
  if (testInfo.project.name === 'mobile') {
    await page.setViewportSize({ width: 320, height: 568 })
    await expect(confirm).toBeInViewport({ ratio: 1 })
    await expect(minutes).toBeInViewport({ ratio: 1 })
  }
  await page.getByRole('button', { name: /^更改日期/ }).click()
  await expect(page.getByRole('gridcell').first()).toBeVisible()
  await expect(confirm).toBeInViewport({ ratio: 1 })
  await page.getByRole('button', { name: '选择时间', exact: true }).click()
  await expect(minutes).toBeVisible()
  await minutes.press('Escape')
  await expect(minutes).toBeHidden()
})

test('数字输入支持建议值快捷选择与时长滚轮', async ({ page }) => {
  await page.goto('/zh/behavior')
  await page.getByRole('button', { name: '＋ 训练' }).click()
  const dialog = page.getByRole('dialog')
  const duration = dialog.getByLabel('时长（分钟）', { exact: true })
  await expect(duration).toHaveValue('30')
  await dialog.getByRole('button', { name: '慢步', exact: true }).click()
  await expect(duration).toHaveValue('30')
  await dialog.getByRole('button', { name: '拉伸', exact: true }).click()
  await expect(duration).toHaveValue('30')
  await dialog.getByRole('group', { name: '时长（分钟）建议值', exact: true }).getByRole('button', { name: '30', exact: true }).click()
  await expect(duration).toHaveValue('30')

  await dialog.getByRole('button', { name: '选择时长（分钟）' }).click()
  const minutes = page.getByRole('spinbutton', { name: '分钟', exact: true })
  await expect(minutes).toHaveAttribute('aria-valuenow', '30')
  await minutes.press('End')
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(duration).toHaveValue('59')
  await page.locator('form').getByRole('button', { name: '取消', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: '分钟', exact: true })).toHaveCount(0)

  await page.getByRole('button', { name: '＋ 睡眠' }).click()
  await dialog.getByRole('group', { name: '睡眠分数建议值', exact: true }).getByRole('button', { name: '70', exact: true }).click()
  await expect(dialog.getByLabel('睡眠分数', { exact: true })).toHaveValue('70')
  await dialog.getByLabel('睡眠时长（小时）', { exact: true }).fill('7')
  await dialog.getByLabel('睡眠时长（分钟）', { exact: true }).fill('30')
  await dialog.getByRole('button', { name: '睡眠时长（分钟） +' }).click()
  await expect(dialog.getByLabel('睡眠时长（分钟）', { exact: true })).toHaveValue('35')
  await dialog.getByRole('button', { name: '睡眠时长（分钟） −' }).click()
  await expect(dialog.getByLabel('睡眠时长（小时）', { exact: true })).toHaveValue('7')
  await expect(dialog.getByLabel('睡眠时长（分钟）', { exact: true })).toHaveValue('30')
  await page.locator('form').getByRole('button', { name: '取消', exact: true }).click()
})

test('指标管理使用明确的新增和编辑状态', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop')
  await page.goto('/zh/metrics')
  await page.getByRole('button', { name: '新增指标' }).click()
  await page.getByLabel('指标名称').fill('睡眠质量')
  await page.getByLabel('指标编码').fill('sleep_quality')
  await page.getByLabel('单位').fill('分')
  await page.getByRole('button', { name: '保存指标' }).click()

  const row = page.locator('article').filter({ hasText: 'sleep_quality' })
  await expect(row).toBeVisible()
  await row.getByRole('button', { name: '编辑' }).click()
  await expect(row.getByLabel('名称')).toHaveValue('睡眠质量')
  await expect(row.getByRole('button', { name: '保存' })).toBeDisabled()
})

test('桌面端和手机端均可维护训练与睡眠记录', async ({ page }, testInfo) => {
  await page.goto('/zh/behavior')
  const duration = testInfo.project.name === 'mobile' ? 47 : 46
  await page.getByRole('button', { name: '＋ 训练' }).click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button', { name: '力量', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '慢步', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '拉伸', exact: true })).toBeVisible()
  await expect(dialog.getByRole('button', { name: '复制上一条' })).toHaveCount(0)
  await expect(dialog.getByText('训练时间', { exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('主观强度（1–10）')).toHaveCount(0)
  await dialog.getByLabel('时长（分钟）', { exact: true }).fill(String(duration))
  await dialog.getByRole('button', { name: '保存记录' }).click()
  await expect(dialog).toBeHidden()

  const record = page.locator('tr:visible, article:visible').filter({ hasText: `${duration} 分钟` }).filter({ has: page.getByRole('button', { name: '编辑' }) }).first()
  await expect(record).toBeVisible()
  await record.getByRole('button', { name: '编辑' }).click()
  await dialog.getByLabel('时长（分钟）', { exact: true }).fill(String(duration + 1))
  await dialog.getByRole('button', { name: '保存记录' }).click()

  const updated = page.locator('tr:visible, article:visible').filter({ hasText: `${duration + 1} 分钟` }).filter({ has: page.getByRole('button', { name: '删除' }) }).first()
  await expect(updated).toBeVisible()
  page.once('dialog', prompt => prompt.accept())
  await updated.getByRole('button', { name: '删除' }).click()
  await expect(updated).toHaveCount(0)

  await page.getByRole('button', { name: '＋ 睡眠' }).click()
  await dialog.getByLabel('睡眠时长（小时）', { exact: true }).fill('7')
  await dialog.getByLabel('睡眠时长（分钟）', { exact: true }).fill('30')
  await dialog.getByLabel('睡眠分数', { exact: true }).fill('80')
  await dialog.getByRole('button', { name: '保存记录' }).click()
  const sleepRecord = page.locator('tr:visible, article:visible').filter({ hasText: '分数 80' }).filter({ has: page.getByRole('button', { name: '编辑' }) }).first()
  await expect(sleepRecord).toBeVisible()
  await sleepRecord.getByRole('button', { name: '编辑' }).click()
  await dialog.getByLabel('睡眠分数', { exact: true }).fill('90')
  await dialog.getByRole('button', { name: '保存记录' }).click()
  const updatedSleep = page.locator('tr:visible, article:visible').filter({ hasText: '分数 90' }).filter({ has: page.getByRole('button', { name: '删除' }) }).first()
  await expect(updatedSleep).toBeVisible()
  page.once('dialog', prompt => prompt.accept())
  await updatedSleep.getByRole('button', { name: '删除' }).click()
  await expect(updatedSleep).toHaveCount(0)
})

test('数据接口使用 ETag 阻止过期覆盖', async ({ request }) => {
  const login = await request.post('/api/auth/login', { data: { username: 'admin', password: 'admin-pass' } })
  expect(login.ok()).toBe(true)
  const initial = await request.get('/api/data')
  expect(initial.ok()).toBe(true)
  const etag = initial.headers().etag
  expect(etag).toBeTruthy()
  const data = await initial.json()

  const saved = await request.put('/api/data', { headers: { 'If-Match': etag }, data })
  expect(saved.ok()).toBe(true)

  const conflict = await request.put('/api/data', { headers: { 'If-Match': etag }, data })
  expect(conflict.status()).toBe(409)
})
